apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-fthm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-fthm
    app.kubernetes.io/part-of: mashas-app-1
  name: devfile-sample-python-basic-fthm
  namespace: marialeonova-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-python-basic-fthm
    weight: null
status: {}
